### PR TITLE
Added config file for Welcome BOT

### PR DESCRIPTION
**Pull request by muthuannamalai12**
I have added a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.

### CODE REVIEW

**Comment by rockingrohit9639** [comment]
Thank you @muthuannamalai12

**Comment by rockingrohit9639** [comment]
Hii @muthuannamalai12, are you in my discord server?

**Comment by muthuannamalai12** [comment]
> Hii @muthuannamalai12, are you in my discord server?

Yes, I am in your discord server.

**Comment by rockingrohit9639** [comment]
> > Hii @muthuannamalai12, are you in my discord server?
> 
> Yes, I am in your discord server.

@muthuannamalai12 Can you drop me a message?

**Pull request merged**
