### PR TITLE
Updated Contributor.md

### PR DESCRIPTION
**Pull request by vishwast03**
I have updated Contributor.md file as you have described.

### CODE REVIEW

**Comment by rockingrohit9639** [comment]
Bro, have you joined CrossWinter of Code

**Comment by vishwast03** [comment]
@rockingrohit9639 
No bro I did not find the link. Please send me the link to that.

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639
> No bro I did not find the link. Please send me the link to that.

Here is the link to apply - https://crosswoc.ieeedtu.in/participant.html

**Comment by vishwast03** [comment]
@rockingrohit9639 
Ok, I will apply. Thanks for the link.
Please merge my pull request.

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639
> Ok, I will apply. Thanks for the link.
> Please merge my pull request.

Join our Discord server, we can talk more there.
I will merge your PR.

**Comment by vishwast03** [comment]
Ok
Please provide me the link to Discord server.

**Comment by rockingrohit9639** [comment]
> Ok
> Please provide me the link to Discord server.

Here is the link - https://discord.gg/GycEMxYm

**Comment by vishwast03** [comment]
Thanks, I will join that.
Make sure to merge my pr soon.

**Comment by vishwast03** [comment]
I have joined the Discord server.

**Pull request closed without merging**
